### ISSUE TITLE
[toolsupdate] 重复打开的串口设备

### ISSUE THREAD

**Issue by NumbNutN** [miraculin1/Drone_uCOS#5]
#commit b63e3b4f
https://github.com/miraculin1/Drone_uCOS/blob/b63e3b4f7629708eb0bc42e22ded9caeb8a33206/tools/betterAttitude.py#L14-L17

将串行接口设备文件打开后保持打开可以持续读取，没必要在每次readline()后关闭并再次打开
将Serial对象的创建提出至回调函数外部或许可以减少一些系统调用开销

**Comment by miraculin1** [comment]
fixed
